enum bxi_log_type {
    // Messages types
    S4BXILOG_E2E_ACK,
    S4BXILOG_PTL_ACK,
    S4BXILOG_PTL_GET_RESPONSE,
    S4BXILOG_PTL_PUT,
    S4BXILOG_PTL_GET,
    S4BXILOG_PTL_ATOMIC,
    S4BXILOG_PTL_FETCH_ATOMIC,
    S4BXILOG_PTL_FETCH_ATOMIC_RESPONSE,

    // PCI operations
    S4BXILOG_PCI_PIO_PAYLOAD,
    S4BXILOG_PCI_DMA_PAYLOAD,
    S4BXILOG_PCI_DMA_REQUEST,
    S4BXILOG_PCI_PAYLOAD_WRITE,
    S4BXILOG_PCI_EVENT,
    S4BXILOG_PCI_COMMAND,

    // Compute operations
    S4BXILOG_COMPUTE,
};